title: DAX
description: Learn DAX
template:
  repo: dax-template
  name: dax
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.closed
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
